import React, { Component } from 'react'

export default class UserSkills extends Component {
    render() {
        return (
            <div>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe maxime eius nemo quas ipsam voluptatum accusantium reprehenderit maiores qui placeat facilis, voluptatem quia, corrupti nobis quasi quis. Cum quis tenetur nostrum consequatur porro autem libero vero veniam deleniti tempore molestiae ullam esse, debitis distinctio vel quaerat dignissimos aliquid, provident vitae architecto, dolore atque quibusdam reiciendis. Eum voluptate vero dignissimos mollitia animi magnam eligendi quis vitae aliquid, minus nisi tempore ipsum explicabo ipsam obcaecati aperiam quo sint, rem accusamus inventore quam id laudantium quaerat! Adipisci fugiat quisquam perferendis excepturi fuga ut dolorum corrupti et culpa, ratione nulla maiores consequuntur labore possimus neque laboriosam vitae totam magnam alias fugit. Voluptas libero, odio temporibus dicta doloribus reprehenderit officia molestias accusantium dolorem, repellat dolores. Iusto autem in dolorum harum voluptates accusamus nostrum est laboriosam repellendus unde velit, quidem odit quis, mollitia nesciunt repudiandae? Deleniti repellat nisi reprehenderit quidem magni quasi in molestiae omnis hic qui quaerat iste autem labore, perferendis natus sapiente, aliquid sit rerum. Quae, nobis ullam, natus ducimus quo enim maiores aliquam iure suscipit odio quaerat magnam qui, labore repudiandae repellat eaque ipsam sapiente. Totam ut tenetur provident. Magnam quis accusantium repellat natus ipsum voluptate corrupti dolor. Velit sapiente autem vitae ad a consequatur perferendis officiis doloremque ullam necessitatibus deleniti rem laboriosam voluptatem dolorem consequuntur, dolor maiores totam nulla similique. Quia numquam maxime facere animi officia debitis asperiores dolor dolorem nihil ducimus architecto, a culpa vitae laudantium ipsum eveniet doloribus necessitatibus aliquam dolorum enim beatae ut minima tenetur sed. Asperiores possimus magni corporis, maxime esse vero cum laudantium incidunt repellat laborum tenetur quod dolor quibusdam porro sequi consequuntur ducimus fugit quasi commodi omnis qui harum accusantium maiores. Consequatur ab et atque quae. Inventore quos totam nesciunt, dolorum facere voluptas esse aspernatur illo similique molestiae cum sit quis fuga quas veniam nulla dignissimos eum repudiandae voluptatem vel voluptate quod ut, officiis reprehenderit. Animi, voluptatem eos dolor iure facilis repellat error quisquam porro quibusdam illum, maiores fugit ipsam. Magnam veniam ad et dolorem consequatur porro est iste eos earum iusto ratione quis repellendus fuga sunt ex, ipsum neque ut. Eos voluptate ipsam enim ex. Deleniti aspernatur quam exercitationem, veniam eum quo non perferendis pariatur, optio provident iure necessitatibus velit eos veritatis placeat quos. Itaque ratione, id hic, pariatur aperiam esse ea culpa sed ipsa quis laudantium porro. Quia magni earum saepe, autem labore maiores odit id amet. Harum, minus fugiat? Optio, quas repudiandae. Tempore.
            </div>
        )
    }
}
