import React, { Component } from 'react'

export default class UserExperience extends Component {
    render() {
        return (
            <div>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, soluta amet blanditiis modi neque illo cum excepturi! Nobis maiores aliquam odit libero, ipsam cumque! Beatae, qui! Amet minima temporibus ducimus corrupti quidem, eaque porro soluta ex illum ullam reiciendis ab enim sunt quos saepe possimus deleniti fuga eveniet, suscipit quibusdam aliquid voluptatibus! Fugit ipsum explicabo recusandae dignissimos quibusdam, ratione debitis quo, quaerat assumenda beatae inventore? Consequatur assumenda itaque minus expedita cupiditate quidem ad quam ducimus ea sint, quasi adipisci voluptatibus magni tempore fugiat in suscipit aliquid, iusto est, voluptatem doloremque at rerum aperiam? Voluptas repellendus mollitia distinctio odio laudantium ut quis nostrum consequuntur nisi vero, corrupti consequatur ea autem. Assumenda illo saepe, voluptates ea inventore id. Sequi omnis doloremque veniam asperiores, totam unde nobis possimus numquam sunt dolores eum at distinctio ullam iusto corporis ab animi quos. Totam incidunt quas corporis ea sed quia vel eligendi animi nam accusamus iste reiciendis, laboriosam, eos exercitationem, illo sunt quod amet obcaecati? Assumenda sint molestias quis animi vero ullam sapiente impedit, quasi facilis et voluptates beatae? Debitis sint quod perspiciatis sequi, similique et nisi a beatae molestiae non laboriosam quasi illo rerum voluptate eligendi dolores modi alias ad error nesciunt dolor quam architecto voluptas. Cum sed blanditiis quasi assumenda, voluptas incidunt perspiciatis nesciunt provident, accusantium veritatis ipsum. Magnam quia hic quis inventore molestias amet recusandae, asperiores qui! Impedit debitis voluptate eligendi natus aliquid facilis cumque doloremque amet, perferendis ipsum, officiis enim sunt deserunt ab ut totam consequatur alias. Laudantium, iure temporibus. Nostrum nisi quam nobis reprehenderit quidem, eius velit dicta cupiditate repellendus veniam earum molestias illum repellat dolore porro, voluptatibus omnis ut qui voluptas dolores laborum id odio reiciendis. Sed, quae tempora! Ad iste est minus totam ea a alias, quisquam inventore sunt maiores, minima provident distinctio dolorem dolor beatae tenetur ipsum veritatis.
            </div>
        )
    }
}
